### ISSUE TITLE
Add more sites support

### ISSUE THREAD

**Issue by elboletaire** [elboletaire/manga-downloader#1]
Add support for more sites

English and multi:
- [x] TCBScans [.net](https://www.tcbscans.net/) [.org](tcbscans.org)
- [x] [tcbscans.com](https://tcbscans.com/) 
- [x] ~~[mangaplus.shueisha.co.jp](https://mangaplus.shueisha.co.jp) uses protobuf for encoding~~
- [x] [Mangadex](https://mangadex.org/)
- [x] [AsuraScans](https://www.asurascans.com)
- [x] [Leviatan Scans](https://en.leviatanscans.com/home/)
- [x] [LH Translation](https://lhtranslation.net)
- [ ] [Manga4Life](https://manga4life.com/)
- [x] [MangaBat](https://h.mangabat.com/)
- [x] [MangaJar](https://mangajar.com)
- [ ] [MangaHere](http://www.mangahere.cc)
- [x] [Manga Monks](https://mangamonks.com)
- [x] [Manganelos](http://manganelos.com/)
- [x] [mangapanda.in](https://mangapanda.in/)
- [ ] [mangapanda.onl](https://mangapanda.in) returns error 403 😕 
- [ ] [MangaPark](https://mangapark.net/)

Italian:
- [ ] [LupiTeam](https://lupiteam.net/)
- [ ] [Juin Jutsu Team Reader](https://juinjutsureader.ovh)

Russian:
- [ ] [MangaLib](https://mangalib.me)

If you plan to start a grabber implementation, either comment here or create an issue for that specific grabber, so it doesn't collide with me (I feel like I'm speaking alone.. but who knows 😅)

PS: Will be enlarging this list as I find more sites. For now I'm ignoring japanese sites, but will be in the list too sooner or later.

**Comment by elboletaire** [comment]
I've decided I won't give support for mangaplus for now, since they only show the very first & last three books, and it's too much time consuming given all the requirements (because it has the data protobufed).

I've also been trying with aurascans, but for some reason that I still don't understand that site does return a 403 error from the go http client (whilst doing it via curl does not). I'll try again at some point, but any clue would be welcome.

**Comment by AkechiiYEETS** [comment]
Hey, TCB's website is [this one](https://onepiecechapters.com) not [this](https://www.tcbscans.net/)

**Comment by elboletaire** [comment]
Well there are actually like 3 or 4 more sites named TCBScans, it's not my work to verify which one is one, but I can try to also add support for the site you provided too.

**Comment by AkechiiYEETS** [comment]
> Well there are actually like 3 or 4 more sites named TCBScans, it's not my work to verify which one is one, but I can try to also add support for the site you provided too.

That'd be great, thanks!

**Comment by elboletaire** [comment]
> > Well there are actually like 3 or 4 more sites named TCBScans, it's not my work to verify which one is one, but I can try to also add support for the site you provided too.
> 
> That'd be great, thanks!

@AkechiiYEETS seems like the website is not hosting mangas anymore (it actually redirects to a one piece news site). Do you know if they changed the link or they simply removed the content?

**Comment by AkechiiYEETS** [comment]
> > > Well there are actually like 3 or 4 more sites named TCBScans, it's not my work to verify which one is one, but I can try to also add support for the site you provided too.
> > 
> > 
> > That'd be great, thanks!
> 
> @AkechiiYEETS seems like the website is not hosting mangas anymore (it actually redirects to a one piece news site). Do you know if they changed the link or they simply removed the content?

Hey, I funnily enough, I believe they've rebranded to [tcbscans.com](https://tcbscans.com/) so a .com instead of .net as the fake version!

**Comment by elboletaire** [comment]
Thanks @AkechiiYEETS. I've added tcbscans.com to the list.

**Comment by elboletaire** [comment]
I'm closing this to prioritize requests from users. If you want one of the listed sites to be added, please, open a new issue.
