### ISSUE TITLE
My Hero Academia on some of the listed supported sites return an invalid syntax error: parsing ""

### ISSUE THREAD

**Issue by Panthon13** [elboletaire/manga-downloader#17]
I get this error with the examples below, but the error seems to be specific to My Hero Academia from what I've tested:

Errors fetching chapters:
strconv.ParseFloat: parsing "": invalid syntax

My Hero Academia - MangaBat
(I tried Attack on Titan, that downloads fine)
manga-downloader-v0.0.9-windows-amd64>manga-downloader.exe https://readmangabat.com/read-ov357862 1
Errors fetching chapters:
strconv.ParseFloat: parsing "": invalid syntax

My Hero Academia - Manganato
(I tried Made in Abyss, that downloads fine)
manga-downloader.exe https://chapmanganato.com/manga-jq951973 1
Errors fetching chapters:
strconv.ParseFloat: parsing "": invalid syntax

My Hero Academia - Manganelo
(I tried Made in Abyss and that downloads fine)
manga-downloader.exe https://ww5.manganelo.tv/manga/manga-jq951973 1
Errors fetching chapters:
strconv.ParseFloat: parsing "": invalid syntax

**Comment by elboletaire** [comment]
Damn, I see the problem... they decided to spam people using a chapter without number

![imatge](https://user-images.githubusercontent.com/153305/213766774-2bd9a308-a1cb-4abe-8f88-f3b1901e6594.png)

Given these sites always show their chapter number and they only do not for these cases... I'll catch the error and just ignore it instead.

**Comment by elboletaire** [comment]
Fixed in #20 and #21. I'll try to fix #19 before creating a new release tho.
