### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by vdo** [elboletaire/manga-downloader#23]
Add a Dockerfile so it can be used directly from ghcr or dockerhub :)

**Comment by elboletaire** [comment]
It's a good idea actually, but how would you recommend me tell users to download stuff using docker? Mounting `$PWD` as volume? i.e.:

~~~bash
docker run --rm -it -v $PWD:/app elboletaire/manga-downloader [command args]
~~~

**Comment by vdo** [comment]
Yes you would mount some local dir to the container to download the stuff. Like in this example:

https://github.com/tnk4on/yt-dlp#get-mp4-video
