### ISSUE TITLE
Issues with quotations in title

### ISSUE THREAD

**Issue by Sirnight282** [elboletaire/manga-downloader#29]
Chapters that include quotation marks in the title give an error saying " error saving file The World God Only Knows 240 - Chapter 240 ; The Present Time "tsukiyo&shiori".cbz: open The World God Only Knows 240 - Chapter 240 ; The Present Time "tsukiyo&shiori".cbz: The filename, directory name, or volume label syntax is incorrect. " I assume this is an issue with Windows not allowing " in filenames, and tried looking into the help command for changing the output name using --filename-template but the help command on my CMD for some reason is a bit of a mess  to read, lots of random symbols and numbers injected into the lines, and I have tried a few naming templates, but it keeps saying it needs at least 1 arg and received 0.
![image](https://github.com/elboletaire/manga-downloader/assets/78249414/ebead4c4-8049-4470-ad79-64eb9fa22f3e)

**Comment by Sirnight282** [comment]
Also apologies if this isn't the place / format for this kind of thing, I've never used this aspect of Github

**Comment by elboletaire** [comment]
Please provide a link for a manga title I could use for testing.

**Comment by Sirnight282** [comment]
Sorry, should've thought about that. Here is one of the chapters that has the problem:
https://ww7.mangakakalot.tv/chapter/manga-ev957056/chapter-240

**Comment by elboletaire** [comment]
I'll take a look as soon as I can (which could be next week btw... time will say). Shouldn't be hard to track, probably some sanitization missing at some point.

**Comment by Sirnight282** [comment]
Awesone, thank you

**Comment by elboletaire** [comment]
Could you please provide more details on how are you exactly downloading the chapters? Because I cannot reproduce the issue :thinking:

**Comment by Sirnight282** [comment]
I just enter in the terminal:
manga-downloader https://ww7.mangakakalot.tv/chapter/manga-ev957056/chapter-240

Currently whenever I try with the site it says site not recognized though, the site was down for a week or so, so I think they may have changed some infrastructure stuff that is messing with the program. I tried finding other sites with quotes in the same chapter title but can't find any in the supported sites list that work at the moment (though I think this may just be an issue with my specific machine)

**Comment by elboletaire** [comment]
> I just enter in the terminal: manga-downloader [ww7.mangakakalot.tv/chapter/manga-ev957056/chapter-240](https://ww7.mangakakalot.tv/chapter/manga-ev957056/chapter-240)

That should not work because you're specifying a chapter url instead of the series one. The command you should use is:

```bash
manga-downloader https://ww7.mangakakalot.tv/manga/manga-ev957056 240
```

Which fails with the provided error. I'll take a look when I can, I'm sorry I'm kinda busy these days and I cannot give the app the love it deserves.
