### ISSUE TITLE
[Question] Does manga-downloader handle updated chapters?

### ISSUE THREAD

**Issue by Lreaper** [elboletaire/manga-downloader#34]
Hi, I'm really excited to try this out and I have a few questions:

1) How does manga-downloader handle chapter updates? Let's say you have downloaded chapters 1 through 10 of a certain series from mangadex, but then the uploader reuploads chapters 7 through 10 with better quality, uncensored etc. Will these reuploaded chapters get downloaded or skipped 8since the filename already exists)
2) Do you intend to possibly create an arm64 docker image?

Thanks!

**Comment by elboletaire** [comment]
> How does manga-downloader handle chapter updates? Let's say you have downloaded chapters 1 through 10 of a certain series from mangadex, but then the uploader reuploads chapters 7 through 10 with better quality, uncensored etc. Will these reuploaded chapters get downloaded or skipped 8since the filename already exists)

The program is quite simple here. It always tries to download what you request it, there's no cache whatsoever. And if the file exists with the same name, it'll just be replaced (not asking for confirmation, so you may want to be careful there).

> Do you intend to possibly create an arm64 docker image?

I'll try https://github.com/elboletaire/manga-downloader/issues/35 :)

**Comment by elboletaire** [comment]
Oh wait, you were asking for an arm64 docker image... not an arm binary like I said in the created issue 😅 

I'll properly update the issue
