### ISSUE TITLE
Feature Request: Define delay timer

### ISSUE THREAD

**Issue by eswiig** [elboletaire/manga-downloader#36]
Hi, I really like manga-downloader but

I'm getting error code 42 often when downloading from mangadex

The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time

Is there a way to set a delay timer in between each request? if not, could there be?

**Comment by elboletaire** [comment]
You can try reducing the concurrency level by using --concurrency 1 --concurrency-pages 2.

By default, these are set to 5 and 10, respectively, which might be triggering the rate limiting errors. Could you please try adjusting these settings and let me know which configuration works best for you? I believe they have recently enforced their rate limit restrictions more strictly, as it was functioning without issues not long ago

**Comment by eswiig** [comment]
`? Do you want to download all 29 chapters? [y/N] y█
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 Л                                                                                                   екція, яку б не хотілося почути від батьків
- downloading Chapter 0001 Лекція, яку б не хотілося почути від батьків pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001
- downloading Chapter 0001 pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 I                                                                                                   l sermone che non vorresti mai ricevere dai tuoi genitori
- downloading Chapter 0001 Il sermone che non vorresti mai ricevere dai tuoi gen                                                                                                   itori pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001
- downloading Chapter 0001 pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 Л                                                                                                   екция, которую вы бы не хотели услышать от своих родителей
- downloading Chapter 0001 Лекция, которую вы бы не хотели услышать от своих род                                                                                                   ителей pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 B                                                                                                   ài thuyết giáo mà ta không bao giờ muốn nghe từ phụ huynh
- downloading Chapter 0001 Bài thuyết giáo mà ta không bao giờ muốn nghe từ phụ                                                                                                    huynh pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 T                                                                                                   he Lecture You Would Never Want Your Parents To Give You
- downloading Chapter 0001 The Lecture You Would Never Want Your Parents To Give                                                                                                    You pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 C                                                                                                   hapter 1
- downloading Chapter 0001 Chapter 1 pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 T                                                                                                   he lecture that you never want your parents to give you
- downloading Chapter 0001 The lecture that you never want your parents to give                                                                                                    you pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001
- downloading Chapter 0001 pages...
^C
nuc@100x001:~/Apps/manga-downloader$ ./manga-downloader https://mangadex.org/tit                                                                                                   le/3cbc4293-3623-470a-9405-f46b328c83d4/the-lecture-you-would-never-want-your-pa                                                                                                   rents-to-give-you --concurrency 1 --concurrency-pages 2 --bundle --language en
Do you want to download all 29 chapters: y
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 T                                                                                                   he Lecture You Would Never Want Your Parents To Give You
- downloading Chapter 0001 The Lecture You Would Never Want Your Parents To Give                                                                                                    You pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0001 T                                                                                                   he lecture that you never want your parents to give you
- downloading Chapter 0001 The lecture that you never want your parents to give                                                                                                    you pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0002 T                                                                                                   he mother that hellishly chimes in on the chat with a friend.
- downloading Chapter 0002 The mother that hellishly chimes in on the chat with                                                                                                    a friend. pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0002 P                                                                                                   arents who get involved in conversations with friends and make things hellish.
- downloading Chapter 0002 Parents who get involved in conversations with friend                                                                                                   s and make things hellish. pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0003 T                                                                                                   he pure heart that gave birth to a hellish Open Class Day
- downloading Chapter 0003 The pure heart that gave birth to a hellish Open Clas                                                                                                   s Day pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0003 A                                                                                                    visit to hell born from a pure heart
- downloading Chapter 0003 A visit to hell born from a pure heart pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0004 T                                                                                                   he mother who do the most merciless shift of responsibility in the whole history                                                                                                    of humanity.
- downloading Chapter 0004 The mother who do the most merciless shift of respons                                                                                                   ibility in the whole history of humanity. pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0004
- downloading Chapter 0004 pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0005 A                                                                                                    mother who reports incomprehensible results in the morning.
- downloading Chapter 0005 A mother who reports incomprehensible results in the                                                                                                    morning. pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0005
- downloading Chapter 0005 pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0006 A                                                                                                    mother who would sacrifice herself for the sake of her family.
- downloading Chapter 0006 A mother who would sacrifice herself for the sake of                                                                                                    her family. pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0006
- downloading Chapter 0006 pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0007 A                                                                                                    mother who just doesn't know what to do anymore
- downloading Chapter 0007 A mother who just doesn't know what to do anymore pag                                                                                                   es...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0007
- downloading Chapter 0007 pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0008 A                                                                                                    mother who smashes her daughter's heart to pieces as she mediates their lover's                                                                                                    quarrel
- downloading Chapter 0008 A mother who smashes her daughter's heart to pieces a                                                                                                   s she mediates their lover's quarrel pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0009 A                                                                                                    mother who sincerely lends an ear to her child's opinion
- downloading Chapter 0009 A mother who sincerely lends an ear to her child's op                                                                                                   inion pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0010 A                                                                                                    mother who carefully and corteously answers a difficult question to answer
- downloading Chapter 0010 A mother who carefully and corteously answers a diffi                                                                                                   cult question to answer pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0011 P                                                                                                   arents and the mystery of the calendar.
- downloading Chapter 0011 Parents and the mystery of the calendar. pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0012 H                                                                                                   onest parents who don't lie to their child
- downloading Chapter 0012 Honest parents who don't lie to their child pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0013 H                                                                                                   onest parents who don't lie to their child
- downloading Chapter 0013 Honest parents who don't lie to their child pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0014 M                                                                                                   ysterious nickname given to parents
- downloading Chapter 0014 Mysterious nickname given to parents pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0015 A                                                                                                    parental lesson "Life is more fun if you let go of shame"
- downloading Chapter 0015 A parental lesson "Life is more fun if you let go of                                                                                                    shame" pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0015
- downloading Chapter 0015 pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0016 P                                                                                                   arents who participate willingly in pagan religious events
- downloading Chapter 0016 Parents who participate willingly in pagan religious                                                                                                    events pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0017 P                                                                                                   arent seriously injured in unexpected accident
- downloading Chapter 0017 Parent seriously injured in unexpected accident pages                                                                                                   ...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0018 P                                                                                                   arents who close the door before going to bed
- downloading Chapter 0018 Parents who close the door before going to bed pages.                                                                                                   ..
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0019 T                                                                                                   he energetic kid who mediates the parent's relationship
- downloading Chapter 0019 The energetic kid who mediates the parent's relations                                                                                                   hip pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0020 T                                                                                                   he Parent that got into a verbal conflict with the young guys in town
- downloading Chapter 0020 The Parent that got into a verbal conflict with the y                                                                                                   oung guys in town pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0021 T                                                                                                   he Bentou shop owner trying his best to suppress his inner evil thoughts
- downloading Chapter 0021 The Bentou shop owner trying his best to suppress his                                                                                                    inner evil thoughts pages...
fetched The Lecture You Would Never Want Your Parents To Give You Chapter 0022 P                                                                                                   arents and the mystery of the calendar (Continuous version)
- downloading Chapter 0022 Parents and the mystery of the calendar (Continuous v                                                                                                   ersion) pages...
- error fetching chapter Parents teach not to judge people by their appearance:                                                                                                    received 429 response code
- error fetching chapter A mysterious tragedy born from love on Valentine's day:                                                                                                    received 429 response code
- error fetching chapter A very secure house: received 429 response code
- error fetching chapter Parents’ favorite development of the sport game: receiv                                                                                                   ed 429 response code
- error fetching chapter A household taking it's health quite seriously.: receiv                                                                                                   ed 429 response code
- error fetching chapter The Rumored Elegant Mother & Daughter in the Neighbourh                                                                                                   ood: received 429 response code
- error fetching chapter A family spending April Fools' Day together happily: re                                                                                                   ceived 429 response code
- saved file The Lecture You Would Never Want Your Parents To Give You  - bundle                                                                                                   .cbz
`

**Comment by elboletaire** [comment]
Have you tried setting both to 1? Maybe with both set to 1 does not ban you (or at least not that fast).

Still, I'll have to give it a try and maybe consider adding a delay, at least for this one, as you suggested.

**Comment by eswiig** [comment]
setting both to 1 worked on a 29 chapter long manga. I will try with some longer ones and let you know how it goes.

**Comment by elboletaire** [comment]
> edit: worked on a 36 chapter manga, seems this option works for now. will update only if I run into the error again.

Let's close the issue then. Feel free to open it if you face with issues again :)
