### ISSUE TITLE
Mangadex Wrong Language

### ISSUE THREAD

**Issue by loli067** [elboletaire/manga-downloader#43]
When a manga has multiple translations, it automatically picks the first one. For example, if it has Russian, Indian, and English translations, it will pick Russian, which is very annoying. Fix this bug by either allowing users to choose their preferred language or by only downloading the English translations.

In the picture below, this manga has multiple translations, and because Chinese was the first, it will be Chinese that is downloaded.
![image](https://github.com/elboletaire/manga-downloader/assets/133435955/6fad3c81-e45d-40bb-b0f8-4b2797cfc06f)

**Comment by loli067** [comment]
I don't know if that's turkey or china think it's turkey I looked at it wrong but doesn't change the issue.

**Comment by loli067** [comment]
Okay this is my fault for not reading the readme lmao.

**Comment by elboletaire** [comment]
When no language is specified, it should download all the languages. If you experienced that is probably because all have the same name, and it downloads all of them replacing the previous ones.
