### ISSUE TITLE
For MangaDex - able to download our lists

### ISSUE THREAD

**Issue by andku85** [elboletaire/manga-downloader#46]
In mangadex. can you make a option for me to download "MyMDList" and also the "Library List" in some type of json file so i can export to excel or something. would like to have a copy from the site.

i am sure it is doable. need to copy the login token import it and select what to download.

mangadex api
https://api.mangadex.org/docs/

this would also be good for the other ones as well with login options.
mangabuddy

**Comment by elboletaire** [comment]
No, or at least not in a near future. This app does not connect to any API, nor has any type of auth nor login to any of the sites. It's just a grabber and I don't plan on extending it outside of its current capabilities.

I'll add new sites and fix the support for others, but this functionality you're asking requires adding a set of new features that, for now, would be only for one or maybe two of the almost 20 sites supported. I don't feel it's worth the effort rn.
