### ISSUE TITLE
windows cant open exe? follow here

### ISSUE THREAD

**Issue by VortexLrd** [elboletaire/manga-downloader#55]
so if you are dumb like me, couldnt open the file just follow the guide

-you probably downloaded the linus or darwin version so you cant open them believe me i tried.,
-you need to donload windows version at the bottom if you have 64 bit system then download it.
-after that open with cmd or shell or terminal. then write like this 

manga-downloader --language en https://mangadex.org/title/e7eabe96-aa17-476f-b431-2497d5e9d060/black-clover 131-346

if you want to check if it works before download just type manga-downloader help
 you can thank me later chat gpt couldnt help me because my version was wrong.

**Comment by elboletaire** [comment]
Next time [read the readme](https://github.com/elboletaire/manga-downloader?tab=readme-ov-file#installation) 😕

**Comment by VortexLrd** [comment]
> Next time [read the readme](https://github.com/elboletaire/manga-downloader?tab=readme-ov-file#installation) 😕

i seriously read everything and i copied it to chat gpt and copilot ifyouknow and i just couldnt fix the issue bc version was wrong. my bad thanks for kindly reminder.
